#
# for bsp
#

# bsp name
IW_BSP := unknown

# current path
BSP_DIR := oal/bsp

# include path
IW_INCS += $(BSP_DIR)

# sources
IW_SRCS += $(BSP_DIR)/bsp_main.C
IW_SRCS += $(BSP_DIR)/bsp_rtc.c
