#
# for bsp
#

# bsp name
IW_BSP := stm32v2

# current path
BSP_DIR := oal/bsp

# include path
IW_INCS += $(BSP_DIR)

# sources
IW_SRCS += $(BSP_DIR)/bsp_main.c
IW_SRCS += $(BSP_DIR)/bsp_rtc.c
