#
# iw/Makefile
#

# path
IW_DIR := oal/iw

# include
IW_INCS += $(IW_DIR)

# sources
IW_SRCS += $(IW_DIR)/iw_main.c
IW_SRCS += $(IW_DIR)/iw_bsp.c
IW_SRCS += $(IW_DIR)/iw_debug.c
IW_SRCS += $(IW_DIR)/iw_dev.c
IW_SRCS += $(IW_DIR)/iw_dev_batt.c
IW_SRCS += $(IW_DIR)/iw_dev_led.c
IW_SRCS += $(IW_DIR)/iw_dev_net.c
IW_SRCS += $(IW_DIR)/iw_dev_sensor.c
IW_SRCS += $(IW_DIR)/iw_if_adc.c
IW_SRCS += $(IW_DIR)/iw_if_gpio.c
IW_SRCS += $(IW_DIR)/iw_if_i2c.c
IW_SRCS += $(IW_DIR)/iw_if_uart.c
IW_SRCS += $(IW_DIR)/iw_oal_fifo.c
IW_SRCS += $(IW_DIR)/iw_oal_init.c
IW_SRCS += $(IW_DIR)/iw_oal_list.c
IW_SRCS += $(IW_DIR)/iw_oal_mem.c
IW_SRCS += $(IW_DIR)/iw_oal_mutex.c
IW_SRCS += $(IW_DIR)/iw_oal_queue.c
IW_SRCS += $(IW_DIR)/iw_oal_sem.c
IW_SRCS += $(IW_DIR)/iw_oal_task.c
IW_SRCS += $(IW_DIR)/iw_oal_time.c
IW_SRCS += $(IW_DIR)/iw_sys.c
