#
# for os
#

# os name
IW_OS := zephyr

# current path
OS_DIR := oal/kernel

# include path
IW_INCS += $(OS_DIR)

# sources
IW_SRCS += $(OS_DIR)/oal_os.c

include $(OS_DIR)/build-stm32.mk